config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get 'post/new'

  get 'post/show'

  get 'communities/show'

  get 'communities/new'

  get 'communities/edit'

  get '/' => 'sports#index'

  get 'sports/show'

  root 'sports#index'

  resources :sports do
    resources :communities do
      resources :posts do
        resources :comments
      end
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/community.rb
class Community < ActiveRecord::Base
  belongs_to :sport
  has_many :posts

  validates :name, presence: true
  validates :post_code, presence: true
  
  geocoded_by :post_code
  after_validation :geocode 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :community
  has_many :comments
  validates :title, presence: true
  validates :content, presence: true
  validates :user_name, presence: true
end

app/models/sport.rb
class Sport < ActiveRecord::Base

  validates :name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :outdoor, presence: true

  has_many :communities
  has_many :posts, through: :communities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_cache_buster

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def new
    @sport = Sport.find(params[:sport_id])
    @community = Community.find(params[:community_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    sport = Sport.find(params[:sport_id])
    community = Community.find(params[:community_id])
    post = Post.find(params[:post_id])
    comment = post.comments.new params[:comment].permit(:user_name, :content)
    if comment.save
      redirect_to sport_community_post_path(sport, community, post)
    else
      render 'new'
    end
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  def show
    @community = Community.find(params[:id])
    @sport = Sport.find(params[:sport_id])
  end

  def new
    @community = Community.new
    @sport = Sport.find(params[:sport_id])
  end

  def create
    sport = Sport.find(params[:sport_id])
    community = sport.communities.new params[:community].permit(:name, :description, :post_code, :image)
      begin
        community.save
      rescue ActiveRecord::RecordInvalid => e
        flash[:error] = e.record.errors.full_messages.to_sentence
        render :action => "new"
      end
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @sport = Sport.find(params[:sport_id])
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def create
    sport = Sport.find(params[:sport_id])
    community = Community.find(params[:community_id])
    post = community.posts.new params[:post].permit(:user_name, :title, :content)
    if post.save
      redirect_to [sport, community]
    else
      render 'new'
    end
  end

  def show
    @sport = Sport.find(params[:sport_id])
    @community = Community.find(params[:community_id])
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.all
  end

  def show
    @sport = Sport.find(params[:id])
    @communities = @sport.communities
    @latest_posts = @sport.posts.last(3)
    respond_to do |format|
      format.html
      format.json { render json: @communities }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/communities/new.html.erb
<%= form_for [@sport, @community] do |f| %>

  <%= f.label :name  %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :post_code %>
  <%= f.text_field :post_code %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit 'Submit' %>
  
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>
   
      <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/communities/show.html.erb
<div class="community-show-heading">
  <h1><%= link_to @community.sport.name, sport_path(@community.sport), class: 'sport-name' %></h1>
  <h2 id="community-show-name"><%= @community.name %></h2>
  <img src="<%= @community.image %>">
  <%= link_to 'Add a post', new_sport_community_post_path(@sport, @community) %> 
</div>

<div class="community-show-content">
  <% @community.posts.each do |post| %>
    <div class="community-post-item">
      <h3><%= post.title %></h3> 
      <h5>by <%= post.user_name %></h5>
      <div class="post-content">
        <p><%= post.content %></p>
      </div>
      <p>...</p>
      <%= link_to 'Read More', sport_community_post_path(@sport, @community, post) %>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sportify</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <li id='brand-logo'><%= link_to 'SPORTIFY', root_path %></li>
      <li class="nav-link"><%= link_to 'HOME', root_path %></li>
    </nav>
  </header>

<%= yield %>

<footer>
  <li><%= link_to 'SPORTS', sports_path %></li>
  <li><%= link_to 'ABOUT', about_path %></li>
  <li><%= link_to 'CONTACT', contact_path %></li>
</footer>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/posts/new.html.erb
<%= form_for [@sport, @community, @post] do |f| %>

  <%= f.label :user_name  %>
  <%= f.text_field :user_name %>

  <%= f.label :title  %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit 'Submit' %>

<% end %>

app/views/posts/show.html.erb
<div class="post-show-wrapper">
  <div class="post-show-heading">
    <h1><%= link_to @sport.name, sport_path(@sport), class: 'sport-name' %></h1>
    <h2 id="community-show-name"><%= link_to @community.name, sport_community_path(@sport, @community) %></h2>
    <img src="<%= @community.image %>">
  </div>
  <div class="post-show-content">
    <h1><%= @post.title %></h1>
    <h4>by <%= @post.user_name %></h4>
    <p><%= @post.content %></p>

    <h3>Comments</h3>
    <div class="comment-form">
      <%= form_for [@sport, @community, @post, @comment] do |f| %>
        <%= f.label :user_name  %>
        <%= f.text_field :user_name %>

        <%= f.label :content  %>
        <%= f.text_area :content %>

        <%= f.submit 'Submit' %>
      <% end %>  
    </div>  
    <% @post.comments.reverse.each do |comment| %>
      <div class="comment">
        <h3><%= comment.user_name %></h3>
        <p class="time-ago"><%= time_ago_in_words(comment.created_at) %> ago</p>
      </div>
      <div class="comment-content">
        <p><%= comment.content %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/sports/index.html.erb
<div class="sports-index-wrapper">
  <% @sports.each do |sport| %>
    <div class="sport-index" style="background-image: url('<%= sport.image %>')">
      <h5><%= link_to sport.name, sport_path(sport.id), class: 'sport-link-index', data: sport.id %></h5>   
    </div>
  <% end %>

  <div class="greeting">
    <h2>Sportify</h2>
    <h4>connecting you to sports communities nearby</h4>
  </div>
</div>

app/views/sports/show.html.erb
<div class="show-sports-page-info">
  <h2 data-id=<%=@sport.id%>><%= @sport.name %></h2>
  <%= link_to 'Add a new community', new_sport_community_path(@sport) %>  
</div>

<div id="map-canvas"></div>

<div class="sport-communities-all">
  <h3>Communities:</h3>
  <div class="communities-exist">
    <% @sport.communities.each do |community| %>
      <div class="sport-show-communities">
        <p><%= community.name %></p> 
        <%= link_to community.post_code, sport_community_path(@sport, community) %>
      </div>
    <% end %>
  </div>
</div>

<div class="sport-posts">
  <h3>Latest Posts about <%= @sport.name %>:</h3>
  <div class="sport-latest-post">
    <% @latest_posts.each do |post| %>
      <div class="sport-single-post">
        <h4><%= post.community.name %>, <%= post.community.post_code %></h4>
        <p>has a new post:</p>
        <h3><%= post.title.length < 32 ? post.title : post.title.slice(0..30) + '...' %></h3>
        <%= link_to 'Read More', sport_community_post_path(@sport, post.community_id, post) %>
      </div>
    <% end %>
  </div>
</div>